openapi: 3.0.0
info:
  description: QuantConnect Lean Desktop API
  version: "1.0.1-oas3"
  title: Lean Desktop API
paths:
  /api/algorithms:
    get:
      summary: retrieves the list of algorithms
      operationId: getAlgorithms
      description: |
        Retrieves the list of algorithms.
      responses:
        '200':
          description: A collection of algorithms
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AlgorithmItem'
  /api/algorithms/{algorithmid}/backtests:
    get:
      parameters:
        - in: path
          name: algorithmid
          description: algorithm class name
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A collection of backtests
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AlgorithmItem'  
components:
  schemas:
    AlgorithmItem:
      type: object
      properties:
        name:
          type: string
          example: SMACross
